name: Container action flow
on: [push]

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hi there, partners"

  execute-container-action:
    needs: say-hi
    runs-on: ubuntu-latest
    strategy:
      matrix:
        resource: [cpu, memory]
    name: Execute container action
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Docker action
        id: local-docker-action
        uses: ./
        with:
          resource-type: ${{ matrix.resource }}
      - name: Get the outputs from docker action step
        run: echo "${{ matrix.resource }}=${{ steps.local-docker-action.outputs.value }}"
      - name: List files in working directory
        run: ls -al .
